name: Noteable
description: "Now you're able to Note. Noteable."


# Prevent accidental publishing
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.2
  intl: ^0.18.1
  firebase_core: ^2.24.2
  firebase_database: ^10.4.2
  process_run: ^1.2.4
  file_picker: ^8.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1


# App icon configuration (now at root level)
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#4a148c"
    theme_color: "#4a148c"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
  macos:
    generate: true
    image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700